version: '3'
services:
  postgres:
    image: postgres:13-alpine
    build: postgres/
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_bank
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '2345:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    image: sharmatanmay617/simple_bank
    build: simple_bank/
    container_name: simple_bank
    ports:
      - '3000:8080'
    environment:
      PORT: 8080
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: pragya56
      PG_DATABASE: simple_bank
      TOKEN_KEY: Pragya@56
    depends_on:
      - postgres