version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_bank
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: me
      PG_PASSWORD: pragya56
      PG_DATABASE: simple_bank
      TOKEN_KEY: Pragya@56
    depends_on:
      - postgres
