name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: simple_bank
          POSTGRES_PASSWORD: pragya56
        ports:
          - '5432:5432'
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 10s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Creating the tables
        run: node ./migrations/initDB.js
      - name: API testing
        run: npm run test-local
        env:
          PORT: 8080
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: pragya56
          PG_DATABASE: simple_bank
          TOKEN_KEY: Pragya@56
          NODE_ENV: test